// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "cellar": Application User Types
//
// Command:
// $ goagen
// --design=goa-demo/design
// --out=$(GOPATH)/src/goa-demo
// --version=v1.2.0-dirty

package app
